# Generated by Django 4.2.11 on 2026-06-27 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_add_home_one', models.ImageField(upload_to='static/assets/AdsImages')),
                ('banner_add_home_two', models.ImageField(upload_to='static/assets/AdsImages')),
                ('banner_add_category_one', models.ImageField(upload_to='static/assets/AdsImages')),
                ('banner_add_category_two', models.ImageField(upload_to='static/assets/AdsImages')),
                ('banner_add_category_three', models.ImageField(upload_to='static/assets/AdsImages')),
                ('banner_add_category_four', models.ImageField(upload_to='static/assets/AdsImages')),
            ],
            options={
                'db_table': 'app_bannerads',
            },
        ),
        migrations.CreateModel(
            name='HomeCrouselAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crousel_add_img', models.ImageField(upload_to='static/assets/AdsImages')),
            ],
            options={
                'db_table': 'app_homecrouselads',
            },
        ),
        migrations.CreateModel(
            name='AdsListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_email', models.CharField(max_length=255)),
                ('ad_type', models.CharField(choices=[('BA', 'Banner Ads'), ('CA', 'Carousel Ads')], default='BA', max_length=2)),
                ('ad_image', models.ImageField(upload_to='static/assets/ads_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_adslisting',
            },
        ),
    ]
