# Generated by Django 4.2.11 on 2026-07-04 03:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_data_migration'),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adslisting',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='shop_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='directory.shoplisting'),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
