# Generated by Django 5.0.7 on 2026-07-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adslisting_created_at_adslisting_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(choices=[('hero_banner', 'Homepage Hero Banner'), ('category_banner', 'Category Page Banner'), ('sidebar', 'Sidebar'), ('listing_interstitial', 'Between Listings')], max_length=30, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_ads', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_adslot',
            },
        ),
        migrations.AddField(
            model_name='adslisting',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='impressions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='package',
            field=models.CharField(choices=[('basic', 'Basic (3 Days)'), ('standard', 'Standard (7 Days)'), ('premium', 'Premium (30 Days)')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='target_page',
            field=models.CharField(choices=[('hero_banner', 'Homepage Hero Banner'), ('category_banner', 'Category Page Banner'), ('sidebar', 'Sidebar'), ('listing_interstitial', 'Between Listings')], default='hero_banner', max_length=30),
        ),
        migrations.AlterField(
            model_name='adslisting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], default='pending', max_length=20),
        ),
    ]
