# Generated by Django 4.2.11 on 2026-09-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_adslot_adslisting_clicks_adslisting_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingVideoAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Feature of the day', max_length=255)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram')], default='youtube', max_length=20)),
                ('video_url', models.URLField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_floatingvideoadvertisement',
                'ordering': ['-created_at'],
            },
        ),
    ]
