# Generated by Django 4.2.11 on 2026-09-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_floatingvideoadvertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslisting',
            name='badge_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='banner_type',
            field=models.CharField(blank=True, default='promotional', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='category_slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='cta_text',
            field=models.CharField(blank=True, default='Explore Now', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='cta_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adslisting',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
