# Generated by Django 4.2.11 on 2026-09-22 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0005_adslisting_badge_text_adslisting_banner_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Client or business name providing the banner', max_length=255)),
                ('website_url', models.URLField(help_text='Destination URL when banner is clicked', max_length=500)),
                ('banner_image', models.ImageField(help_text='Banner graphic asset', upload_to='banners/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('badge_text', models.CharField(blank=True, max_length=50, null=True)),
                ('cta_text', models.CharField(blank=True, default='Explore Now', max_length=50, null=True)),
                ('start_date', models.DateField(db_index=True)),
                ('expiry_date', models.DateField(db_index=True)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_banner',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_enabled', 'start_date', 'expiry_date'], name='app_banner_is_enab_834209_idx')],
            },
        ),
    ]
