# Generated by Django 4.2.11 on 2026-09-24 07:52

import apps.ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adslisting',
            name='ad_image',
            field=models.ImageField(upload_to='static/assets/ads_images', validators=[apps.ads.models.validate_banner_image_size]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=models.ImageField(help_text='Banner graphic asset (max 1 MB)', upload_to='banners/', validators=[apps.ads.models.validate_banner_image_size]),
        ),
        migrations.AlterField(
            model_name='banner',
            name='website_url',
            field=models.URLField(blank=True, help_text='Destination URL when banner is clicked', max_length=500, null=True),
        ),
    ]
