# Generated by Django 4.2.11 on 2026-06-27 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_img', models.ImageField(upload_to='static/assets/category_img')),
                ('img_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'app_categoryimg',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(max_length=50)),
                ('category_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.categoryimg')),
            ],
            options={
                'db_table': 'app_maincategory',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=50)),
                ('sub_category_img', models.ImageField(upload_to='static/assets/category_img')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.maincategory')),
            ],
            options={
                'db_table': 'app_subcategory',
            },
        ),
        migrations.CreateModel(
            name='ShopListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('business_rating', models.IntegerField(default=0)),
                ('business_address', models.CharField(max_length=100)),
                ('business_banner', models.ImageField(upload_to='static/assets/listedShops')),
                ('sub_domain_one', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_domain_two', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_domain_three', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_domain_four', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_domain_five', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_domain_six', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_domain_seven', models.CharField(blank=True, max_length=50, null=True)),
                ('business_origin', models.CharField(default='India', max_length=50)),
                ('business_dob', models.CharField(default='N/A', max_length=50)),
                ('business_gst', models.CharField(default='N/A', max_length=50)),
                ('business_description', models.CharField(max_length=1000)),
                ('business_img_one', models.ImageField(upload_to='static/assets/listedShops')),
                ('business_img_two', models.ImageField(upload_to='static/assets/listedShops')),
                ('business_img_three', models.ImageField(upload_to='static/assets/listedShops')),
                ('business_no', models.CharField(max_length=15)),
                ('business_email', models.CharField(max_length=50)),
                ('insta_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('website_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('gmap_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.maincategory')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_shoplisting',
            },
        ),
        migrations.CreateModel(
            name='LikedShops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.shoplisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_likedshops',
            },
        ),
    ]
