# Generated by Django 4.2.11 on 2026-07-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplisting',
            name='business_origin',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='business_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='city',
            field=models.CharField(default='Jalgaon', max_length=50),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='trending_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='trending_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shoplisting',
            name='business_img_one',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/listedShops'),
        ),
        migrations.AlterField(
            model_name='shoplisting',
            name='business_img_three',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/listedShops'),
        ),
        migrations.AlterField(
            model_name='shoplisting',
            name='business_img_two',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/listedShops'),
        ),
        migrations.CreateModel(
            name='BusinessPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/assets/listedShops/gallery')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='directory.shoplisting')),
            ],
            options={
                'db_table': 'app_businessphoto',
            },
        ),
    ]
