# Generated by Django 4.2.11 on 2026-07-03 11:11

from django.db import migrations
from django.utils.text import slugify
import uuid

def migrate_data(apps, schema_editor):
    ShopListing = apps.get_model('directory', 'ShopListing')
    MainCategory = apps.get_model('directory', 'MainCategory')
    SubCategory = apps.get_model('directory', 'SubCategory')

    for category in MainCategory.objects.all():
        if not category.slug:
            category.slug = slugify(category.main_category)
            # handle duplicates
            base_slug = category.slug
            count = 1
            while MainCategory.objects.filter(slug=category.slug).exists():
                category.slug = f"{base_slug}-{count}"
                count += 1
            category.save()

    for subcategory in SubCategory.objects.all():
        if not subcategory.slug:
            subcategory.slug = slugify(subcategory.sub_category)
            # handle duplicates
            base_slug = subcategory.slug
            count = 1
            while SubCategory.objects.filter(slug=subcategory.slug).exists():
                subcategory.slug = f"{base_slug}-{count}"
                count += 1
            subcategory.save()

    for listing in ShopListing.objects.all():
        # 1. Slug
        if not listing.slug:
            base_slug = slugify(listing.business_name)
            listing.slug = f"{base_slug}-{str(uuid.uuid4())[:8]}"

        # 2. Status
        if listing.is_valid:
            listing.status = 'active'
        else:
            listing.status = 'pending'

        # 3. Social links consolidation
        social_links = {}
        if listing.insta_link:
            social_links['instagram'] = listing.insta_link
        if listing.facebook_link:
            social_links['facebook'] = listing.facebook_link
        if listing.website_link:
            social_links['website'] = listing.website_link
        
        listing.social_links = social_links
        
        listing.save()

class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_remove_shoplisting_business_origin_maincategory_slug_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data, reverse_code=migrations.RunPython.noop),
    ]
