# Generated by Django 4.2.11 on 2026-07-04 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0003_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='directory.shoplisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_businessclaim',
                'ordering': ['-created_at'],
            },
        ),
    ]
