# Generated by Django 4.2.11 on 2026-07-04 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0004_businessclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake', 'Fake/Spam Business'), ('inappropriate', 'Inappropriate Content'), ('closed', 'Business Permanently Closed'), ('wrong_info', 'Incorrect Information'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_reports', to=settings.AUTH_USER_MODEL)),
                ('shop_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='directory.shoplisting')),
            ],
            options={
                'db_table': 'app_businessreport',
                'ordering': ['-created_at'],
            },
        ),
    ]
