# Generated by Django 4.2.13 on 2026-07-04 11:44
# Generated by Django 4.2.11 on 2026-07-04 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_businessreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='category_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.categoryimg'),
        ),
    ]
