# Generated by Django 4.2.11 on 2026-07-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_maincategory_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplisting',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='shoplisting',
            name='meta_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='shoplisting',
            name='business_name',
            field=models.CharField(max_length=150),
        ),
    ]
