# Generated by Django 5.0.7 on 2026-07-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplisting',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
