# Generated by Django 5.0.7 on 2026-08-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_shoplisting_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplisting',
            name='business_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
