# Generated by Django 4.2.11 on 2026-07-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOImageAlt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('alt_text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Image Alt Text',
                'verbose_name_plural': 'SEO Image Alt Texts',
                'db_table': 'app_seoimagealt',
            },
        ),
    ]
