# Generated by Django 4.2.11 on 2026-07-04 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_data_migration'),
        ('jobs', '0002_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='shop_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='directory.shoplisting'),
        ),
    ]
