# Generated by Django 5.0.7 on 2026-08-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_shop_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
