# Generated by Django 5.0.7 on 2026-08-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='custom_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='custom_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
