# Generated by Django 5.0.7 on 2026-08-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_custom_questions_jobapplication_custom_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='custom_questions',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='custom_answers',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
