# Generated by Django 4.2.11 on 2026-07-03 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_remove_shoplisting_business_origin_maincategory_slug_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopreview',
            name='is_helpful_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='rating_star',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='shop_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='directory.shoplisting'),
        ),
    ]
