# Generated by Django 5.0.7 on 2026-07-10 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_shopreview_is_helpful_count_shopreview_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopreview',
            name='rating_star',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
