# Generated by Django 4.2.11 on 2026-07-09 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_job_shop_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0008_enable_pg_trgm'),
        ('ads', '0003_adslot_adslisting_clicks_adslisting_end_date_and_more'),
        ('news', '0005_alter_newsarticle_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('platform', 'Platform-Wide'), ('listing', 'Per Listing'), ('ad', 'Per Ad Campaign')], max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('total_views', models.IntegerField(default=0)),
                ('unique_views', models.IntegerField(default=0)),
                ('search_queries', models.IntegerField(default=0)),
                ('ad_impressions', models.IntegerField(default=0)),
                ('ad_clicks', models.IntegerField(default=0)),
                ('contact_clicks', models.IntegerField(default=0)),
                ('new_listings', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('new_reviews', models.IntegerField(default=0)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.adslisting')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.shoplisting')),
            ],
            options={
                'db_table': 'analytics_daily_report',
                'unique_together': {('report_type', 'date', 'listing', 'ad')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('listing_view', 'Listing Profile View'), ('listing_search', 'Search Query'), ('listing_click', 'Listing Card Click'), ('ad_impression', 'Ad Impression'), ('ad_click', 'Ad Click'), ('job_view', 'Job View'), ('news_view', 'News Article View'), ('event_view', 'Event View'), ('contact_click', 'Contact Button Click'), ('review_submit', 'Review Submitted')], db_index=True, max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('referrer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.adslisting')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.shoplisting')),
                ('news_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.newsarticle')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_event',
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_ef40a5_idx'), models.Index(fields=['listing', 'created_at'], name='analytics_e_listing_33bc89_idx'), models.Index(fields=['ad', 'created_at'], name='analytics_e_ad_id_929e3f_idx')],
            },
        ),
    ]
