# Generated by Django 4.2.11 on 2026-06-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_title', models.CharField(max_length=50)),
                ('stock_price', models.CharField(max_length=50)),
                ('isUp', models.BooleanField()),
                ('stock_change', models.CharField(max_length=50)),
                ('stock_price_percentage', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'app_financedata',
            },
        ),
    ]
