# Generated by Django 4.2.11 on 2026-06-27 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_desc', models.CharField(max_length=100)),
                ('blog_img', models.ImageField(upload_to='static/assets/article_imgs')),
                ('para_one', models.CharField(max_length=1000)),
                ('para_two', models.CharField(max_length=1000)),
                ('para_trhee', models.CharField(max_length=1000)),
                ('para_four', models.CharField(max_length=1000)),
                ('para_five', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'app_articlemodel',
            },
        ),
        migrations.CreateModel(
            name='ActiveArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.articlemodel')),
            ],
            options={
                'db_table': 'app_activearticle',
            },
        ),
    ]
