# Generated by Django 4.2.11 on 2026-07-01 07:45

import uuid
from django.db import migrations
from django.utils.text import slugify
from django.utils import timezone

def migrate_articles(apps, schema_editor):
    ArticleModel = apps.get_model('news', 'ArticleModel')
    ActiveArticle = apps.get_model('news', 'ActiveArticle')
    NewsArticle = apps.get_model('news', 'NewsArticle')

    # Get active article IDs
    active_ids = set(ActiveArticle.objects.values_list('article_id', flat=True))

    for article in ArticleModel.objects.all():
        # Combine paragraphs into content
        content = "\n\n".join(filter(None, [
            article.para_one,
            article.para_two,
            article.para_trhee, # Handle typo in legacy model
            article.para_four,
            article.para_five
        ]))
        
        # Generate slug
        base_slug = slugify(article.title)
        slug = base_slug
        if not slug:
            slug = f"article-{uuid.uuid4().hex[:8]}"
            
        # Ensure unique slug
        counter = 1
        while NewsArticle.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        is_active = article.id in active_ids

        NewsArticle.objects.create(
            title=article.title,
            short_description=article.short_desc,
            content=content,
            featured_image=article.blog_img,
            status='published',
            is_breaking=is_active,
            published_at=timezone.now(),
            slug=slug
        )

def reverse_migrate(apps, schema_editor):
    NewsArticle = apps.get_model('news', 'NewsArticle')
    NewsArticle.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_newscategory_newstag_newscomment_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_articles, reverse_migrate),
    ]

