# Generated by Django 4.2.11 on 2026-07-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_migrate_legacy_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
