# Generated by Django 4.2.11 on 2026-07-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newscomment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=300, unique=True),
        ),
    ]
