# Generated by Django 5.0.7 on 2026-07-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, help_text='The root word users might type (lowercase)', max_length=100, unique=True)),
                ('synonyms', models.JSONField(default=list, help_text='JSON array of synonym strings, e.g. ["clinic", "hospital"]')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'search_synonym',
                'ordering': ['term'],
            },
        ),
    ]
