# Generated by Django 4.2.11 on 2026-06-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('content_manager', 'Content Manager'), ('news_editor', 'News Editor'), ('seo_manager', 'SEO Manager'), ('moderator', 'Moderator'), ('support', 'Support Executive'), ('advertiser', 'Advertiser'), ('business_owner', 'Business Owner'), ('registered_user', 'Registered User'), ('guest', 'Guest')], default='registered_user', max_length=30),
        ),
    ]
