# Generated by Django 5.0.7 on 2026-07-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short user bio shown on their public profile.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True after phone number is confirmed via OTP.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional email address for account recovery and notifications.', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=13)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('was_successful', models.BooleanField(default=False)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'auth_login_attempt',
                'indexes': [models.Index(fields=['phone_number', 'attempted_at'], name='auth_login__phone_n_89efe4_idx'), models.Index(fields=['ip_address', 'attempted_at'], name='auth_login__ip_addr_72a395_idx')],
            },
        ),
    ]
